### ISSUE TITLE
Sometimes it shows the batterybar when it is switched off

### ISSUE THREAD

**Issue by Dzakus** [zst123/XuiMod#16]
1. Enable BatteryBar
2. Reboot
3. Disable BatteryBar
4. Wait, wait and...
   Sometimes it shows the batterybar when it is switched off

Proof: https://www.dropbox.com/sc/lfisbh4xu123c5g/PRCRWoX6-e
Version: 1.6

**Comment by zst123** [comment]
Fixed. @c25a241599bd4c6b1d804012697b298c756b10c6
